spring.application.name=hotelesrt-backend
server-port=8080


#MySQL Central
spring.datasource.central.url=jdbc:mysql://localhost:3306/hotelesrt_central?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.central.username= root
spring.datasource.central.password=
spring.datasource.central.driver-class-name=com.mysql.cj.jdbc.driver

#SQLite
hoteles.db.path=hoteles/

#JWT 
jwt.secret=hotelesrt_1234hert
jwt.expiration = 86400000