spring.application.name=hotelesrt-backend
server-port=8080


#MySQL Central
spring.datasource.central.url=jdbc:mysql://localhost:3306/hotelesrt_central?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.central.username= root
spring.datasource.central.password=
spring.datasource.central.driver-class-name=com.mysql.cj.jdbc.driver

#SQLite
hoteles.db.path=hoteles/

#JWT 
jwt.secret=hotelesrt_1234hert_contraseñaquetienequesermuylargaporquesinodaerrorentoncesmepongoaescribiraquihastaquesellene
jwt.expiration = 86400000


spring.main.allow-bean-definition-overriding=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG

spring.web.resources.static-locations=classpath:/static/,file:D:/PI2/hotelesrt-backend/imagenes
