INSERT INTO habitaciones (numero, tipo, capacidad, precioNoche, descripcion, imagenUrl, disponible, version) VALUES


-- 40 Dobles (30 Piso 1 y 10 Piso 2)
('101', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('102', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('103', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('104', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('105', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('106', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('107', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('108', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('109', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('110', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('111', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('112', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('113', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('114', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('115', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('116', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('117', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('118', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('119', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('120', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('121', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('122', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('123', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('124', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('125', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('126', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('127', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('128', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('129', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('150', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('201', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('202', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('203', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('204', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('205', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('206', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('207', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('208', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('209', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),
('210', 'DOBLE', 2, 90.0, 'Habitación doble con dos camas individuales.', '/imagenes/habitaciones/bilbao/Doble', 1, 0),

-- 30 Doble M (20 Piso 2 y 10 Piso 3)
('211', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('212', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('213', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('214', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('215', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('216', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('217', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('218', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('219', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('220', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('221', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('222', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('223', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('224', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('225', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('226', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('227', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('228', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('229', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('230', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('301', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('302', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('303', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('304', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('305', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('306', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('307', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('308', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('309', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),
('310', 'DOBLEM', 2, 150.0, 'Habitación doble con cama matrimonial.', '/imagenes/habitaciones/bilbao/DobleM', 1, 0),

-- 18 Familiar

('311', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('312', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('313', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('314', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('315', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('316', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('317', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('318', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('319', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('320', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('321', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('322', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('323', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('324', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('325', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('326', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('327', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),
('328', 'FAMILIAR', 2, 210.0, 'Habitación familiar con cama matrimonial, cama individual y una gran zona de estar.', '/imagenes/habitaciones/bilbao/Familiar', 1, 0),


-- 10 Suites 
('401', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('402', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('403', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('404', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('405', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('406', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('407', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('408', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('409', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0),
('410', 'SUITE', 2, 299.0, 'Suite de lujo con salón independiente, muy espaciosa y con todo tipo de comodidades.', '/imagenes/habitaciones/bilbao/Suite', 1, 0);